### ISSUE TITLE
Support setting pod states in a query

### ISSUE THREAD

**Issue by tyrylu** [Genbox/WolframAlphaNet#4]
Hello,
your API seems quite nice, but i was not able to found a way how to specify the pod states for a particular WA query which i would like to do in one of my projects. Of course, i could have overlooked something and any help would also be much appreciated.

**Comment by Genbox** [comment]
What do you mean by setting the state on a specific pod? Usually you make a query, and the results come back in pods, which are controlled by the WA backend.

**Comment by tyrylu** [comment]
I meant specifing the more and other states which alter the result somehow.
